source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RSDSerialization_Example', :exclusive => true do
  pod "RSDSerialization", :path => "../"
end

target 'RSDSerialization_Tests', :exclusive => true do
  pod "RSDSerialization", :path => "../"

  
end
